[project]
name = "pystructconf-rule-engine"
version = "0.0.1"
description = "Rule evaluation/marking for pyStructConf (depends on core)."
readme = "../../README.md"
requires-python = ">=3.10,<3.14"
license = { file = "../../LICENSE" }
authors = [{ name = "chingyaw" }]
dependencies = [
  "pystructconf-core>=0.0.1",
]

[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pystructconf_rule_engine"]
