[project]
name = "pystructconf-core"
version = "0.0.1"
description = "Core abstractions and data models for pyStructConf."
readme = "../../README.md"
requires-python = ">=3.9,<3.15"
license = { file = "../../LICENSE" }
authors = [{ name = "chingyaw" }]
dependencies = []

[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pystructconf_core"]
