name: CI
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]  # 3.14 not on ubuntu-latest yet
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install workspace
        run: |
          uv pip install -e ./packages/core
          uv pip install -e ./packages/rule-engine
          uv pip install -e ./packages/cli
          uv pip install -e ./packages/integrations-fastapi

      - name: Install test tools
        run: uv pip install pytest

      - name: Run tests
        run: pytest -q
